function text=generate_text_input_summary(filename,TimeDomainData, tau_vector, T_vector, t_vector,variable_vector)  
NumDim=size(TimeDomainData);
NumDim=length(NumDim);

if NumDim==4
text=strvcat(' ',filename,['Time Domain Data Size: ' num2str(size(TimeDomainData))],...
    ['tau vector size ' num2str(length(tau_vector))],...
    ['T vector size ' num2str(length(T_vector))],...
    ['t vector size ' num2str(length(t_vector))]);
elseif NumDim==5
    text=strvcat(' ',filename,['Time Domain Data Size: ' num2str(size(TimeDomainData))],...
    ['tau vector size ' num2str(length(tau_vector))],...
    ['T vector size ' num2str(length(T_vector))],...
    ['t vector size ' num2str(length(t_vector))],...
    ['variable vector size ' num2str(length(variable_vector))]);
else 
    text='Input Error!';
end