function text=generate_text_input_summary_SpecDomain(SpecDomainData, w_tau_vector, w_t_vector)  

text=strvcat('Input Summary',['Spectral Domain Data Size: ' num2str(size(SpecDomainData))],...
    ['omega_tau vector size ' num2str(length(w_tau_vector))],...
    ['omega_t vector size ' num2str(length(w_t_vector))]);