Description of plot_square
Home > CMDSworld > subfunctions > plot_functions > plot_square.m
plot_square
PURPOSE
SYNOPSIS
function plot_square(X,Y,Color)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
plotfunction_2D_spec_1Q1Q
plotfunction_Time_Domain_maps this plot function plot Time Domain Maps tau vs t for T_increment of
TwoD_def_ROI watch out: x axis in plot is t axis in plot
SOURCE CODE
function plot_square(X,Y,Color)
w=X(2)-X(1);
h=Y(2)-Y(1);
if nargin<3
rectangle('Position',[X(1),Y(1),w,h],'LineWidth',1.5);
%     if w==0 && h==0
%         scatter(X(1),Y(1),'X');
%     end
else
rectangle('Position',[X(1),Y(1),w,h],'LineWidth',1.5,'EdgeColor',Color);
    if w==1 && h==1
        scatter(X(1),Y(1),'X');
    end
end