Description of TwoDspec1Q1Q
Home > CMDSworld > subguis > TwoDspec1Q1Q.m
TwoDspec1Q1Q
PURPOSE
TWODSPEC1Q1Q MATLAB code for TwoDspec1Q1Q.fig
SYNOPSIS
function varargout = TwoDspec1Q1Q(varargin)
DESCRIPTION
 TWODSPEC1Q1Q MATLAB code for TwoDspec1Q1Q.fig
      TWODSPEC1Q1Q, by itself, creates a new TWODSPEC1Q1Q or raises the existing
      singleton*.
      H = TWODSPEC1Q1Q returns the handle to a new TWODSPEC1Q1Q or the handle to
      the existing singleton*.
      TWODSPEC1Q1Q('CALLBACK',hObject,eventData,handles,...) calls the local
      function named CALLBACK in TWODSPEC1Q1Q.M with the given input arguments.
      TWODSPEC1Q1Q('Property','Value',...) creates a new TWODSPEC1Q1Q or raises the
      existing singleton*.  Starting from the left, property value pairs are
      applied to the GUI before TwoDspec1Q1Q_OpeningFcn gets called.  An
      unrecognized property name or invalid value makes property application
      stop.  All inputs are passed to TwoDspec1Q1Q_OpeningFcn via varargin.
      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
      instance to run (singleton)".
 See also: GUIDE, GUIDATA, GUIHANDLES
CROSS-REFERENCE INFORMATION
This function calls:
CMDSworld CMDSWORLD MATLAB code for CMDSworld.fig
T_scan_evaluation T_SCAN_EVALUATION MATLAB code for T_scan_evaluation.fig
modal_exit_question MODAL_EXIT_QUESTION MATLAB code for modal_exit_question.fig
Calculate_and_plot_1Q1Q
TwoD_def_ROI watch out: x axis in plot is t axis in plot
UpdateFigure
generate_list_entries
get_operation_from_list_entry
setinvisible
check_input_data
This function is called by:
CMDSworld CMDSWORLD MATLAB code for CMDSworld.fig
SUBFUNCTIONS
function TwoDspec1Q1Q_OpeningFcn(hObject, eventdata, handles, varargin)
function varargout = TwoDspec1Q1Q_OutputFcn(hObject, eventdata, handles)
function listbox_contribution_spec_plot1_Callback(hObject, eventdata, handles)
function listbox_contribution_spec_plot1_CreateFcn(hObject, eventdata, handles)
function listbox_contribution_spec_plot2_Callback(hObject, eventdata, handles)
function listbox_contribution_spec_plot2_CreateFcn(hObject, eventdata, handles)
function listbox_contribution_spec_plot3_Callback(hObject, eventdata, handles)
function listbox_contribution_spec_plot3_CreateFcn(hObject, eventdata, handles)
function radio_normalization_Callback(hObject, eventdata, handles)
function radio_normalization_CreateFcn(hObject, eventdata, handles)
function Menu_File_Callback(hObject, eventdata, handles)
function Menu_Units_Callback(hObject, eventdata, handles)
function Menu_file_fs_rad_fs_Callback(hObject, eventdata, handles)
function Menu_file_fs_THz_Callback(hObject, eventdata, handles)
function Menu_file_fs_eV_Callback(hObject, eventdata, handles)
function Menu_file_fs_wavenumber_Callback(hObject, eventdata, handles)
function Menu_file_copy_all_to_figures_Callback(hObject, eventdata, handles)
function Menu_file_copy_selected_to_figure_Callback(hObject, eventdata, handles)
function Menu_File_Save_All_Figure_and_Data_Callback(hObject, eventdata, handles)
function Menu_File_Save_selected_figure_and_data_Callback(hObject, eventdata, handles)
function Menu_Exit_Callback(hObject, eventdata, handles)
function Menu_Data_Settings_Callback(hObject, eventdata, handles)
function Menu_Data_Settings_Normalization_Callback(hObject, eventdata, handles)
function edit_zero_padding_image_Callback(hObject, eventdata, handles)
function edit_zero_padding_image_CreateFcn(hObject, eventdata, handles)
function Menu_Zero_Padding_Callback(hObject, eventdata, handles)
function edit_zero_padding_contour_Callback(hObject, eventdata, handles)
function edit_zero_padding_contour_CreateFcn(hObject, eventdata, handles)
function radiobutton_units_eV_Callback(hObject, eventdata, handles)
function radiobutton_units_meV_Callback(hObject, eventdata, handles)
function radiobutton_Units_Hz_Callback(hObject, eventdata, handles)
function radiobutton_units_GHz_Callback(hObject, eventdata, handles)
function radiobutton_Units_THz_Callback(hObject, eventdata, handles)
function radiobutton_Units_PHz_Callback(hObject, eventdata, handles)
function Menu_plot_settings_Callback(hObject, eventdata, handles)
function radiobutton_plot_contour_Callback(hObject, eventdata, handles)
function Menu_Plot_settings_countour_lines_Callback(hObject, eventdata, handles)
function edit_number_of_lines_Callback(hObject, eventdata, handles)
function edit_number_of_lines_CreateFcn(hObject, eventdata, handles)
function slider_T_scan_Callback(hObject, eventdata, handles)
function slider_T_scan_CreateFcn(hObject, eventdata, handles)
function radiobutton_active_figure1_Callback(hObject, eventdata, handles)
function radiobutton_active_figure1_CreateFcn(hObject, eventdata, handles)
function radiobutton_active_figure3_Callback(hObject, eventdata, handles)
function radiobutton_active_figure2_Callback(hObject, eventdata, handles)
function Menu_Data_Def_ROI_Callback(hObject, eventdata, handles)
function pushbutton_add_ROI_Callback(hObject, eventdata, handles)
function listbox_ROIs_Callback(hObject, eventdata, handles)
function listbox_ROIs_CreateFcn(hObject, eventdata, handles)
function radiobutton_square_Callback(hObject, eventdata, handles)
function radiobutton_manual_square_Callback(hObject, eventdata, handles)
function radiobutton_fixed_size_Callback(hObject, eventdata, handles)
function radiobutton_Polygon_Callback(hObject, eventdata, handles)
function radiobutton_square_CreateFcn(hObject, eventdata, handles)
function pushbutton_delete_ROI_Callback(hObject, eventdata, handles)
function pushbutton_calc_T_scan_Callback(hObject, eventdata, handles)
function Menu_Data_Gamma_value_Callback(hObject, eventdata, handles)
function edit_gamma_Callback(hObject, eventdata, handles)
function edit_gamma_CreateFcn(hObject, eventdata, handles)
function edit_lambda0_Callback(hObject, eventdata, handles)
function edit_lambda0_CreateFcn(hObject, eventdata, handles)
function slider_variable_scan_Callback(hObject, eventdata, handles)
function slider_variable_scan_CreateFcn(hObject, eventdata, handles)
function text_variable_scan_2_CreateFcn(hObject, eventdata, handles)
function radiobutton_Double_omega_tau_Callback(hObject, eventdata, handles)
function radiobutton_Double_omega_t_Callback(hObject, eventdata, handles)
function radiobutton_spectrum_flip_w_tau_Callback(hObject, eventdata, handles)
function radiobutton_spectrum_flip_w_t_Callback(hObject, eventdata, handles)
function Menu_Plot_settings_flip_axes_Callback(hObject, eventdata, handles)
SOURCE CODE
function varargout = TwoDspec1Q1Q(varargin)
% TWODSPEC1Q1Q MATLAB code for TwoDspec1Q1Q.fig
%      TWODSPEC1Q1Q, by itself, creates a new TWODSPEC1Q1Q or raises the existing
%      singleton*.
%
%      H = TWODSPEC1Q1Q returns the handle to a new TWODSPEC1Q1Q or the handle to
%      the existing singleton*.
%
%      TWODSPEC1Q1Q('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in TWODSPEC1Q1Q.M with the given input arguments.
%
%      TWODSPEC1Q1Q('Property','Value',...) creates a new TWODSPEC1Q1Q or raises the
%      existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before TwoDspec1Q1Q_OpeningFcn gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to TwoDspec1Q1Q_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES
% Edit the above text to modify the response to help TwoDspec1Q1Q
% Last Modified by GUIDE v2.5 27-Nov-2018 16:57:56
% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @TwoDspec1Q1Q_OpeningFcn, ...
                   'gui_OutputFcn',  @TwoDspec1Q1Q_OutputFcn, ...
                   'gui_LayoutFcn',  [] , ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end
if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT
% --- Executes just before TwoDspec1Q1Q is made visible.
function TwoDspec1Q1Q_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to TwoDspec1Q1Q (see VARARGIN)
% Choose default command line output for TwoDspec1Q1Q
handles.output = hObject;
%get data from main gui
maindata=varargin{1};
handles.maindata=maindata;
%check data availability
[checkavail,~]=check_input_data(maindata.TDdata.TimeDomainData,...
    maindata.TDdata.tau_vector,...
    maindata.TDdata.T_vector,...
    maindata.TDdata.t_vector);
if ~isfield(maindata,'pcdata')
    checkavail_phases=false;
    msgbox('No phase-cycling data available.')
elseif isempty(maindata.pcdata)
    checkavail_phases=false;
    msgbox('No phase-cycling data available.')
% elseif length(maindata.pcdata.all_phases{1})~=sizeTD(1)
%     checkavail_phases=false;
%     msgbox('Phase-cycling data set is of incorrect length.')
else
    checkavail_phases=true;
end
if checkavail==false
    error('Data not available!');
elseif checkavail_phases==false
    error('Data not available!');
end
% check wether figure was loaded previously
if ~isfield(maindata,'figuredata')
% default values
handles.misc.number_isovalues=11;
handles.misc.xtitle='auto';
handles.misc.Domain='TimeMap';
handles.misc.operation='absolute';
handles.misc.ytitle='auto';
handles.misc.title='auto';
handles.misc.Normalization='No Normalization';
handles.misc.Units='rad/fs';
handles.misc.ZeropaddingImage=1;
handles.misc.ZeropaddingContour=3;
handles.misc.Contour='on';
handles.ROI.ROI_data_x={};
handles.ROI.ROI_data_y={};
handles.ROI.ROI_mask_data={};
Tpos=1;
PCpos=1;
name_of_scheme='default';
handles.misc.omega_center=0;
handles.misc.gamma=0;
handles.misc.Double_omega_tau='off';
handles.misc.Double_omega_t='off';
handles.misc.Flip_w_tau='off';
handles.misc.Flip_w_t='off';
Varpos=1;
else
handles.misc.number_isovalues=maindata.figuredata.contour_isovalues;
handles.misc.xtitle=maindata.figuredata.XLabel;
handles.misc.Domain=maindata.figuredata.Domain;
handles.misc.operation=maindata.figuredata.operation;
handles.misc.ytitle=maindata.figuredata.YLabel;
handles.misc.title=maindata.figuredata.Title;
handles.misc.Normalization=maindata.figuredata.normalization;
handles.misc.Units=maindata.figuredata.Units;
handles.misc.ZeropaddingImage=maindata.figuredata.Zeropadding_Image;
handles.misc.ZeropaddingContour=maindata.figuredata.Zeropadding_Contour;
handles.misc.Contour=maindata.figuredata.Contour;
    if isfield(maindata.figuredata.ROIdata,'ROI_data_x')
        handles.ROI.ROI_data_x=maindata.figuredata.ROIdata.ROI_data_x;
        handles.ROI.ROI_data_y=maindata.figuredata.ROIdata.ROI_data_y;
        handles.ROI.ROI_mask_data=maindata.figuredata.ROIdata.ROI_mask_data;
            cont={};
            for ii=1:length(handles.ROI.ROI_data_x)
                    x=handles.ROI.ROI_data_x{ii};
                    y=handles.ROI.ROI_data_y{ii};
                    str=['dX=' num2str([min(x), max(x)],' %.2f') ' dY=' num2str([min(y), max(y)],' %.2f')];
                    cont{end+1} = str;
                    set(handles.listbox_ROIs,'String',cont);
                    set(handles.listbox_ROIs,'Value',size(cont,1))
            end
    else
        handles.ROI.ROI_data_x={};
        handles.ROI.ROI_data_y={};
        handles.ROI.ROI_mask_data={};
    end
Tpos=maindata.figuredata.Tpos;
PCpos=maindata.figuredata.PCpos;
name_of_scheme=maindata.figuredata.name_of_scheme;
handles.misc.omega_center=maindata.figuredata.omega_center;
handles.misc.gamma=maindata.figuredata.gamma;
handles.misc.Double_omega_tau=maindata.figuredata.Double_omega_tau;
handles.misc.Double_omega_t=maindata.figuredata.Double_omega_t;
if isfield(maindata.figuredata,'Flip_w_tau') %backward comp.
handles.misc.Flip_w_tau=maindata.figuredata.Flip_w_tau;
handles.misc.Flip_w_t=maindata.figuredata.Flip_w_t;
else
handles.misc.Flip_w_tau='off';
handles.misc.Flip_w_t='off';
end
    if ~isfield(maindata.figuredata,'Varpos')
        Varpos=1;
    else Varpos=maindata.figuredata.Varpos;
    end
end
% Perform Calculate and plot for left figure for the first time (constructor)
[handles.figure_1_data]=Calculate_and_plot_1Q1Q(maindata.TDdata.TimeDomainData,...
    handles.misc.Domain,...
    maindata.TDdata.tau_vector,maindata.TDdata.T_vector,maindata.TDdata.t_vector,...
    maindata.pcdata.all_weights{end},...
    handles.TwoD_1Q1Q_Spectrum1,PCpos,Tpos,handles.misc.operation,...
    handles.misc.Normalization,handles.misc.Units,...
    handles.misc.xtitle,handles.misc.ytitle,'auto',handles.misc.ZeropaddingImage,'on',...
    handles.misc.ZeropaddingContour,handles.misc.number_isovalues,name_of_scheme,handles.ROI,...
    handles.misc.omega_center,handles.misc.gamma,...
    handles.misc.Double_omega_tau,...
    handles.misc.Double_omega_t,...
    handles.misc.Flip_w_tau,...
    handles.misc.Flip_w_t,...
    Varpos);
% Perform Calculate and plot for middle figure for the first time
axes(handles.TwoD_1Q1Q_Spectrum2);
[handles.figure_2_data]=Calculate_and_plot_1Q1Q(maindata.TDdata.TimeDomainData,...
    handles.misc.Domain,...
    maindata.TDdata.tau_vector,maindata.TDdata.T_vector,maindata.TDdata.t_vector,...
    maindata.pcdata.all_weights{end},...
    handles.TwoD_1Q1Q_Spectrum2,PCpos,Tpos,handles.misc.operation,...
    handles.misc.Normalization,handles.misc.Units,...
    handles.misc.xtitle,handles.misc.ytitle,'auto',handles.misc.ZeropaddingImage,'on',...
    handles.misc.ZeropaddingContour,handles.misc.number_isovalues,name_of_scheme,handles.ROI,...
    handles.misc.omega_center,handles.misc.gamma,...
    handles.misc.Double_omega_tau,...
    handles.misc.Double_omega_t,...
    handles.misc.Flip_w_tau,...
    handles.misc.Flip_w_t,...
    Varpos);
% Perform Calculate and plot for right figure for the first time
axes(handles.TwoD_1Q1Q_Spectrum3);
[handles.figure_3_data]=Calculate_and_plot_1Q1Q(maindata.TDdata.TimeDomainData,...
    handles.misc.Domain,...
    maindata.TDdata.tau_vector,maindata.TDdata.T_vector,maindata.TDdata.t_vector,...
    maindata.pcdata.all_weights{end},...
    handles.TwoD_1Q1Q_Spectrum3,PCpos,Tpos,handles.misc.operation,...
    handles.misc.Normalization,handles.misc.Units,...
    handles.misc.xtitle,handles.misc.ytitle,'auto',handles.misc.ZeropaddingImage,'on',...
    handles.misc.ZeropaddingContour,handles.misc.number_isovalues,name_of_scheme,handles.ROI,...
    handles.misc.omega_center,handles.misc.gamma,...
    handles.misc.Double_omega_tau,...
    handles.misc.Double_omega_t,...
    handles.misc.Flip_w_tau,...
    handles.misc.Flip_w_t,...
    Varpos);
% set checkbolean for length(T)
if length(handles.maindata.TDdata.T_vector)>1
handles.boleans.checkT=true;
else handles.boleans.checkT=false;
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% set all slider settings%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SizeTimeDomainData=size(handles.maindata.TDdata.TimeDomainData);
if SizeTimeDomainData(1,3)==1
set(handles.slider_T_scan,'Value',0);
set(handles.slider_T_scan,'Visible','off');
else
set(handles.slider_T_scan,'Min',1)
set(handles.slider_T_scan,'Max',SizeTimeDomainData(1,3));
Max=get(handles.slider_T_scan,'Max');
set(handles.slider_T_scan,'SliderStep',[1/(Max-1) 1/(Max-1)]);
set(handles.slider_T_scan,'Value',1);
end
NumDim=ndims(handles.maindata.TDdata.TimeDomainData);
if NumDim<5
set(handles.slider_variable_scan,'Value',0);
set(handles.slider_variable_scan,'Visible','off');
else
set(handles.slider_variable_scan,'Visible','on');
set(handles.text_variable_scan_2,'Visible','on');
set(handles.slider_variable_scan,'Min',1)
set(handles.slider_variable_scan,'Max',SizeTimeDomainData(1,5));
Max=get(handles.slider_variable_scan,'Max');
set(handles.slider_variable_scan,'SliderStep',[1/(Max-1) 1/(Max-1)]);
set(handles.slider_variable_scan,'Value',1);
end
% Update handles structure
guidata(hObject, handles);
% UIWAIT makes TwoDspec1Q1Q wait for user response (see UIRESUME)
% uiwait(handles.TwoD1Q1Q);
% --- Outputs from this function are returned to the command line.
function varargout = TwoDspec1Q1Q_OutputFcn(hObject, eventdata, handles)
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Get default command line output from handles structure
varargout{1} = handles.output;
% --- Executes on selection change in listbox_contribution_spec_plot1.
function listbox_contribution_spec_plot1_Callback(hObject, eventdata, handles)
% hObject    handle to listbox_contribution_spec_plot1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: contents = cellstr(get(hObject,'String')) returns listbox_contribution_spec_plot1 contents as cell array
%        contents{get(hObject,'Value')} returns selected item from listbox_contribution_spec_plot1
contents = cellstr(get(hObject,'String'));
listentry=contents{get(hObject,'Value')};
if ~isempty(listentry)
[weights1,Domain,operation,name_of_scheme]=get_operation_from_list_entry(listentry,...
    handles.maindata.pcdata.all_weights,...
    handles.maindata.pcdata.all_names_of_scheme);
handles.misc.fig1_name_of_scheme=name_of_scheme;
[handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
    handles.TwoD_1Q1Q_Spectrum1,...
    {'weights' 'Domain' 'operation' 'contour_isovalues' 'name_of_scheme'},{weights1 Domain operation handles.misc.number_isovalues name_of_scheme});
end
guidata(hObject,handles);
% --- Executes during object creation, after setting all properties.
function listbox_contribution_spec_plot1_CreateFcn(hObject, eventdata, handles)
% hObject    handle to listbox_contribution_spec_plot1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: listbox controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
%get data from main gui
maindata=guidata(CMDSworld);
handles.maindata=maindata;
text=generate_list_entries(maindata.pcdata.all_weights,maindata.pcdata.all_names_of_scheme);
set(hObject,'String',text);
handles.listbox_contribution_spec_plot1=text;
guidata(hObject,handles);
% --- Executes on selection change in listbox_contribution_spec_plot2.
function listbox_contribution_spec_plot2_Callback(hObject, eventdata, handles)
% hObject    handle to listbox_contribution_spec_plot2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: contents = cellstr(get(hObject,'String')) returns listbox_contribution_spec_plot2 contents as cell array
%        contents{get(hObject,'Value')} returns selected item from listbox_contribution_spec_plot2
contents = cellstr(get(hObject,'String'));
listentry=contents{get(hObject,'Value')};
if ~isempty(listentry)
[weights1,Domain,operation,name_of_scheme]=get_operation_from_list_entry(listentry,...
    handles.maindata.pcdata.all_weights,...
    handles.maindata.pcdata.all_names_of_scheme);
handles.misc.fig2_name_of_scheme=name_of_scheme;
[handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
    handles.TwoD_1Q1Q_Spectrum2,...
    {'weights' 'Domain' 'operation' 'contour_isovalues' 'name_of_scheme'},{weights1 Domain operation handles.misc.number_isovalues name_of_scheme});
end
guidata(hObject,handles);
% --- Executes during object creation, after setting all properties.
function listbox_contribution_spec_plot2_CreateFcn(hObject, eventdata, handles)
% hObject    handle to listbox_contribution_spec_plot2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: listbox controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
maindata=guidata(CMDSworld);
handles.maindata=maindata;
text=generate_list_entries(maindata.pcdata.all_weights,maindata.pcdata.all_names_of_scheme);
set(hObject,'String',text);
handles.listbox_contribution_spec_plot2=text;
guidata(hObject,handles);
% --- Executes on selection change in listbox_contribution_spec_plot3.
function listbox_contribution_spec_plot3_Callback(hObject, eventdata, handles)
% hObject    handle to listbox_contribution_spec_plot3 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: contents = cellstr(get(hObject,'String')) returns listbox_contribution_spec_plot3 contents as cell array
%        contents{get(hObject,'Value')} returns selected item from listbox_contribution_spec_plot3
contents = cellstr(get(hObject,'String'));
listentry=contents{get(hObject,'Value')};
if ~isempty(listentry)
[weights1,Domain,operation,name_of_scheme]=get_operation_from_list_entry(listentry,...
    handles.maindata.pcdata.all_weights,...
    handles.maindata.pcdata.all_names_of_scheme);
handles.misc.fig3_name_of_scheme=name_of_scheme;
[handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
    handles.TwoD_1Q1Q_Spectrum3,...
    {'weights' 'Domain' 'operation' 'contour_isovalues' 'name_of_scheme'},{weights1 Domain operation handles.misc.number_isovalues name_of_scheme});
end
guidata(hObject,handles);
% --- Executes during object creation, after setting all properties.
function listbox_contribution_spec_plot3_CreateFcn(hObject, eventdata, handles)
% hObject    handle to listbox_contribution_spec_plot3 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: listbox controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
maindata=guidata(CMDSworld);
handles.maindata=maindata;
text=generate_list_entries(maindata.pcdata.all_weights,maindata.pcdata.all_names_of_scheme);
set(hObject,'String',text);
handles.listbox_contribution_spec_plot3=text;
guidata(hObject,handles);
% --- Executes on button press in radio_normalization.
function radio_normalization_Callback(hObject, eventdata, handles)
% hObject    handle to radio_normalization (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hint: get(hObject,'Value') returns toggle state of radio_normalization
if get(hObject,'Value')==0
    handles.misc.normalization='No Normalization';
else
    handles.misc.normalization='Normalization';
end
[handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
    handles.TwoD_1Q1Q_Spectrum1,...
    {'normalization' 'contour_isovalues'},{handles.misc.normalization handles.misc.number_isovalues});
[handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
    handles.TwoD_1Q1Q_Spectrum2,...
    {'normalization' 'contour_isovalues'},{handles.misc.normalization handles.misc.number_isovalues});
[handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
    handles.TwoD_1Q1Q_Spectrum3,...
    {'normalization' 'contour_isovalues'},{handles.misc.normalization handles.misc.number_isovalues});
guidata(hObject,handles);
% --- Executes during object creation, after setting all properties.
function radio_normalization_CreateFcn(hObject, eventdata, handles)
% hObject    handle to radio_normalization (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% --------------------------------------------------------------------
function Menu_File_Callback(hObject, eventdata, handles)
% hObject    handle to Menu_File (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% --------------------------------------------------------------------
function Menu_Units_Callback(hObject, eventdata, handles)
% hObject    handle to Menu_Units (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% --------------------------------------------------------------------
function Menu_file_fs_rad_fs_Callback(hObject, eventdata, handles)
% hObject    handle to Menu_file_fs_rad_fs (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
set(handles.uipanel_Units,'Visible','on');
setinvisible({handles.uibuttongroup_Units_eV handles.uipanel_wavenumber handles.uibuttongroup_units_THz});
set(handles.uipanel_rad_fs,'Visible','on');
handles.misc.units='rad/fs';
[handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
    handles.TwoD_1Q1Q_Spectrum1,...
    {'Units'},{handles.misc.units});
[handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
    handles.TwoD_1Q1Q_Spectrum2,...
    {'Units'},{handles.misc.units});
[handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
    handles.TwoD_1Q1Q_Spectrum3,...
    {'Units'},{handles.misc.units});
guidata(hObject,handles);
% --------------------------------------------------------------------
function Menu_file_fs_THz_Callback(hObject, eventdata, handles)
% hObject    handle to Menu_file_fs_THz (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
set(handles.uipanel_Units,'Visible','on');
setinvisible({handles.uipanel_wavenumber handles.uipanel_rad_fs handles.uibuttongroup_Units_eV});
set(handles.uibuttongroup_units_THz,'Visible','on');
set(handles.radiobutton_Units_THz,'Value',1);
handles.misc.units='THz';
[handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
    handles.TwoD_1Q1Q_Spectrum1,...
    {'Units'},{handles.misc.units});
[handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
    handles.TwoD_1Q1Q_Spectrum2,...
    {'Units'},{handles.misc.units});
[handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
    handles.TwoD_1Q1Q_Spectrum3,...
    {'Units'},{handles.misc.units});
guidata(hObject,handles);
% --------------------------------------------------------------------
function Menu_file_fs_eV_Callback(hObject, eventdata, handles)
% hObject    handle to Menu_file_fs_eV (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
%setinvisible({handles.}
set(handles.uipanel_Units,'Visible','on');
setinvisible({handles.uipanel_wavenumber handles.uipanel_rad_fs handles.uibuttongroup_units_THz});
set(handles.uibuttongroup_Units_eV,'Visible','on');
set(handles.radiobutton_units_meV,'Value',1);
set(handles.radiobutton_units_eV,'Value',0);
handles.misc.units='meV';
[handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
    handles.TwoD_1Q1Q_Spectrum1,...
    {'Units'},{handles.misc.units});
[handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
    handles.TwoD_1Q1Q_Spectrum2,...
    {'Units'},{handles.misc.units});
[handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
    handles.TwoD_1Q1Q_Spectrum3,...
    {'Units'},{handles.misc.units});
guidata(hObject,handles);
% --------------------------------------------------------------------
function Menu_file_fs_wavenumber_Callback(hObject, eventdata, handles)
% hObject    handle to Menu_file_fs_wavenumber (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
set(handles.uipanel_Units,'Visible','on');
setinvisible({handles.uibuttongroup_Units_eV handles.uipanel_rad_fs handles.uibuttongroup_units_THz});
set(handles.uipanel_wavenumber,'Visible','on');
handles.misc.units='wavenumber';
[handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
    handles.TwoD_1Q1Q_Spectrum1,...
    {'Units'},{handles.misc.units});
[handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
    handles.TwoD_1Q1Q_Spectrum2,...
    {'Units'},{handles.misc.units});
[handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
    handles.TwoD_1Q1Q_Spectrum3,...
    {'Units'},{handles.misc.units});
guidata(hObject,handles);
% --------------------------------------------------------------------
function Menu_file_copy_all_to_figures_Callback(hObject, eventdata, handles)
% hObject    handle to Menu_file_copy_all_to_figures (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% --------------------------------------------------------------------
h1=figure('Name','1Q1Q Figure 1','Position',[680   558   468   340]);
copyobj(handles.TwoD_1Q1Q_Spectrum1,h1);
colb=colorbar;
colb.LineWidth=1.5;
colb.TickDirection='out';
colb.FontSize=16;
colb.FontName='Arial';
set(gca,'ActivePositionProperty','outerposition')
set(gca,'Units','normalized')
set(gca,'OuterPosition',[0 0 1 1])
h2=figure('Name','1Q1Q Figure 2','Position',[700   558   468   340]);
copyobj(handles.TwoD_1Q1Q_Spectrum2,h2);
colb=colorbar;
colb.LineWidth=1.5;
colb.TickDirection='out';
colb.FontSize=16;
colb.FontName='Arial';
set(gca,'ActivePositionProperty','outerposition')
set(gca,'Units','normalized')
set(gca,'OuterPosition',[0 0 1 1])
h3=figure('Name','1Q1Q Figure 3','Position',[720   558   468   340]);
copyobj(handles.TwoD_1Q1Q_Spectrum3,h3);
colb=colorbar;
colb.LineWidth=1.5;
colb.TickDirection='out';
colb.FontSize=16;
colb.FontName='Arial';
set(gca,'ActivePositionProperty','outerposition')
set(gca,'Units','normalized')
set(gca,'OuterPosition',[0 0 1 1])
function Menu_file_copy_selected_to_figure_Callback(hObject, eventdata, handles)
% hObject    handle to Menu_file_copy_selected_to_figure (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% --------------------------------------------------------------------
num=handles.misc.active_figure;
if num==1
ax=handles.TwoD_1Q1Q_Spectrum1;
elseif num==2
ax=handles.TwoD_1Q1Q_Spectrum2;
elseif num==3
ax=handles.TwoD_1Q1Q_Spectrum3;
end
h1=figure('Name',['1Q1Q Figure ' num2str(num)],'Position',[680   558   468   340]);
copyobj(ax,h1);
colb=colorbar;
colb.LineWidth=1.5;
colb.TickDirection='out';
colb.FontSize=16;
colb.FontName='Arial';
set(gca,'ActivePositionProperty','outerposition')
set(gca,'Units','normalized')
set(gca,'OuterPosition',[0 0 1 1])
function Menu_File_Save_All_Figure_and_Data_Callback(hObject, eventdata, handles)
% hObject    handle to Menu_File_Save_All_Figure_and_Data (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% --------------------------------------------------------------------
save_dir=uigetdir('M:\');
filename_out=inputdlg({'Set file name'},'',1,{''});
filename_out=fullfile(save_dir,filename_out);
h1=figure('Name','1Q1Q Figure 1','Position',[680   558   468   340]);
copyobj(handles.TwoD_1Q1Q_Spectrum1,h1);
colb=colorbar;
colb.LineWidth=1.5;
colb.TickDirection='out';
colb.FontSize=16;
colb.FontName='Arial';
set(gca,'ActivePositionProperty','outerposition')
set(gca,'Units','normalized')
set(gca,'OuterPosition',[0 0 1 1])
%data are saved in UserData of figure
h1.UserData=handles.figure_1_data;
h2=figure('Name','1Q1Q Figure 2','Position',[700   558   468   340]);
copyobj(handles.TwoD_1Q1Q_Spectrum2,h2);
colb=colorbar;
colb.LineWidth=1.5;
colb.TickDirection='out';
colb.FontSize=16;
colb.FontName='Arial';
set(gca,'ActivePositionProperty','outerposition')
set(gca,'Units','normalized')
set(gca,'OuterPosition',[0 0 1 1])
%data are saved in UserData of figure
h2.UserData=handles.figure_2_data;
h3=figure('Name','1Q1Q Figure 3','Position',[720   558   468   340]);
copyobj(handles.TwoD_1Q1Q_Spectrum3,h3);
colb=colorbar;
colb.LineWidth=1.5;
colb.TickDirection='out';
colb.FontSize=16;
colb.FontName='Arial';
set(gca,'ActivePositionProperty','outerposition')
set(gca,'Units','normalized')
set(gca,'OuterPosition',[0 0 1 1])
set(h1,'PaperPositionMode','auto');
set(h2,'PaperPositionMode','auto');
set(h3,'PaperPositionMode','auto');
%data are saved in UserData of figure
h3.UserData=handles.figure_3_data;
figure_data=handles.figure_1_data;
save([filename_out{1} '_1_CMDSfigure'],'figure_data');
figure_data=handles.figure_2_data;
save([filename_out{1} '_2_CMDSfigure'],'figure_data');
figure_data=handles.figure_3_data;
save([filename_out{1} '_3_CMDSfigure'],'figure_data');
% printeps(get(h1,'Number'),[filename_out{1} '_1']);
saveas(h1,[filename_out{1} '_1_CMDSfigure' '.fig']);
saveas(h1,[filename_out{1} '_1_CMDSfigure' '.pdf']);
saveas(h1,[filename_out{1} '_1_CMDSfigure' '.png']);
% printeps(get(h2,'Number'),[filename_out{1} '_2']);
saveas(h2,[filename_out{1} '_2_CMDSfigure' '.fig']);
saveas(h2,[filename_out{1} '_2_CMDSfigure' '.pdf']);
saveas(h2,[filename_out{1} '_2_CMDSfigure' '.png']);
% printeps(get(h3,'Number'),[filename_out{1} '_3']);
saveas(h3,[filename_out{1} '_3_CMDSfigure' '.fig']);
saveas(h3,[filename_out{1} '_3_CMDSfigure' '.pdf']);
saveas(h3,[filename_out{1} '_3_CMDSfigure' '.png']);
function Menu_File_Save_selected_figure_and_data_Callback(hObject, eventdata, handles)
% hObject    handle to Menu_File_Save_selected_figure_and_data (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% --------------------------------------------------------------------
num=handles.misc.active_figure;
save_dir=uigetdir('M:\');
filename_out=inputdlg({'Set file name'},'',1,{''});
filename_out=fullfile(save_dir,filename_out);
if num==1
ax=handles.TwoD_1Q1Q_Spectrum1;
figure_data=handles.figure_1_data;
elseif num==2
ax=handles.TwoD_1Q1Q_Spectrum2;
figure_data=handles.figure_2_data;
elseif num==3
ax=handles.TwoD_1Q1Q_Spectrum3;
figure_data=handles.figure_3_data;
end
h1=figure('Name',['1Q1Q Figure ' num2str(num)],'Position',[680   558   468   340]);
copyobj(ax,h1);
colb=colorbar;
colb.LineWidth=1.5;
colb.TickDirection='out';
colb.FontSize=16;
colb.FontName='Arial';
set(gca,'ActivePositionProperty','outerposition')
set(gca,'Units','normalized')
set(gca,'OuterPosition',[0 0 1 1])
set(h1,'PaperPositionMode','auto');
h1.UserData=figure_data;
save([filename_out{1} num2str(num) '_CMDSfigure'],'figure_data');
% printeps(get(h1,'Number'),[filename_out{1} num2str(num) '_CMDSfigure']);
saveas(h1,[filename_out{1} num2str(num) '_CMDSfigure.fig']);
saveas(h1,[filename_out{1} num2str(num) '_CMDSfigure.pdf']);
saveas(h1,[filename_out{1} num2str(num) '_CMDSfigure.png']);
function Menu_Exit_Callback(hObject, eventdata, handles)
% hObject    handle to Menu_Exit (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% --------------------------------------------------------------------
out=modal_exit_question;
if strcmp(out,'Yes')
delete(handles.TwoD1Q1Q);
else
end
function Menu_Data_Settings_Callback(hObject, eventdata, handles)
% hObject    handle to Menu_Data_Settings (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% --------------------------------------------------------------------
function Menu_Data_Settings_Normalization_Callback(hObject, eventdata, handles)
% hObject    handle to Menu_Data_Settings_Normalization (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
set(handles.panel_data_settings,'Visible','on');
set(handles.radio_normalization,'Value',1);
handles.misc.normalization='Normalization';
[handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
    handles.TwoD_1Q1Q_Spectrum1,...
    {'normalization' 'contour_isovalues'},{handles.misc.normalization handles.misc.number_isovalues});
[handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
    handles.TwoD_1Q1Q_Spectrum2,...
    {'normalization' 'contour_isovalues'},{handles.misc.normalization handles.misc.number_isovalues});
[handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
    handles.TwoD_1Q1Q_Spectrum3,...
    {'normalization' 'contour_isovalues'},{handles.misc.normalization handles.misc.number_isovalues});
guidata(hObject,handles);
function edit_zero_padding_image_Callback(hObject, eventdata, handles)
% hObject    handle to edit_zero_padding_image (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_zero_padding_image as text
%        str2double(get(hObject,'String')) returns contents of edit_zero_padding_image as a double
handles.misc.zero_padding_image=str2double(get(hObject,'String'));
%check for integer
if floor(handles.misc.zero_padding_image)==handles.misc.zero_padding_image
  [handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
    handles.TwoD_1Q1Q_Spectrum1,...
    {'Zeropadding_Image'},{handles.misc.zero_padding_image});
[handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
    handles.TwoD_1Q1Q_Spectrum2,...
    {'Zeropadding_Image'},{handles.misc.zero_padding_image});
[handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
    handles.TwoD_1Q1Q_Spectrum3,...
    {'Zeropadding_Image'},{handles.misc.zero_padding_image});
end
guidata(hObject,handles);
% --- Executes during object creation, after setting all properties.
function edit_zero_padding_image_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_zero_padding_image (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --------------------------------------------------------------------
function Menu_Zero_Padding_Callback(hObject, eventdata, handles)
% hObject    handle to Menu_Zero_Padding (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
set(handles.panel_data_settings,'Visible','on');
function edit_zero_padding_contour_Callback(hObject, eventdata, handles)
% hObject    handle to edit_zero_padding_contour (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_zero_padding_contour as text
%        str2double(get(hObject,'String')) returns contents of edit_zero_padding_contour as a double
handles.misc.zero_padding_contour=str2double(get(hObject,'String'));
%check for integer
if floor(handles.misc.zero_padding_contour)==handles.misc.zero_padding_contour
  [handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
    handles.TwoD_1Q1Q_Spectrum1,...
    {'Zeropadding_Contour'},{handles.misc.zero_padding_contour});
[handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
    handles.TwoD_1Q1Q_Spectrum2,...
    {'Zeropadding_Contour'},{handles.misc.zero_padding_contour});
[handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
    handles.TwoD_1Q1Q_Spectrum3,...
    {'Zeropadding_Contour'},{handles.misc.zero_padding_contour});
end
guidata(hObject,handles);
% --- Executes during object creation, after setting all properties.
function edit_zero_padding_contour_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_zero_padding_contour (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --- Executes on button press in radiobutton_units_eV.
function radiobutton_units_eV_Callback(hObject, eventdata, handles)
% hObject    handle to radiobutton_units_eV (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hint: get(hObject,'Value') returns toggle state of radiobutton_units_eV
state=get(hObject,'Value');
if state==1
    handles.misc.units='eV';
[handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
    handles.TwoD_1Q1Q_Spectrum1,...
    {'Units'},{handles.misc.units});
[handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
    handles.TwoD_1Q1Q_Spectrum2,...
    {'Units'},{handles.misc.units});
[handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
    handles.TwoD_1Q1Q_Spectrum3,...
    {'Units'},{handles.misc.units});
end
% --- Executes on button press in radiobutton_units_eV.
function radiobutton_units_meV_Callback(hObject, eventdata, handles)
% hObject    handle to radiobutton_units_eV (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hint: get(hObject,'Value') returns toggle state of radiobutton_units_eV
state=get(hObject,'Value');
if state==1
    handles.misc.units='meV';
[handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
    handles.TwoD_1Q1Q_Spectrum1,...
    {'Units'},{handles.misc.units});
[handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
    handles.TwoD_1Q1Q_Spectrum2,...
    {'Units'},{handles.misc.units});
[handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
    handles.TwoD_1Q1Q_Spectrum3,...
    {'Units'},{handles.misc.units});
end
% --- Executes on button press in radiobutton_Units_Hz.
function radiobutton_Units_Hz_Callback(hObject, eventdata, handles)
% hObject    handle to radiobutton_Units_Hz (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
state=get(hObject,'Value');
if state==1
handles.misc.units='Hz';
[handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
    handles.TwoD_1Q1Q_Spectrum1,...
    {'Units'},{handles.misc.units});
[handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
    handles.TwoD_1Q1Q_Spectrum2,...
    {'Units'},{handles.misc.units});
[handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
    handles.TwoD_1Q1Q_Spectrum3,...
    {'Units'},{handles.misc.units});
end
guidata(hObject,handles);
% --- Executes on button press in radiobutton_units_GHz.
function radiobutton_units_GHz_Callback(hObject, eventdata, handles)
% hObject    handle to radiobutton_units_GHz (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hint: get(hObject,'Value') returns toggle state of radiobutton_units_GHz
state=get(hObject,'Value');
if state==1
handles.misc.units='GHz';
[handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
    handles.TwoD_1Q1Q_Spectrum1,...
    {'Units'},{handles.misc.units});
[handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
    handles.TwoD_1Q1Q_Spectrum2,...
    {'Units'},{handles.misc.units});
[handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
    handles.TwoD_1Q1Q_Spectrum3,...
    {'Units'},{handles.misc.units});
end
guidata(hObject,handles);
% --- Executes on button press in radiobutton_Units_THz.
function radiobutton_Units_THz_Callback(hObject, eventdata, handles)
% hObject    handle to radiobutton_Units_THz (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hint: get(hObject,'Value') returns toggle state of radiobutton_Units_THz
state=get(hObject,'Value');
if state==1
handles.misc.units='THz';
[handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
    handles.TwoD_1Q1Q_Spectrum1,...
    {'Units'},{handles.misc.units});
[handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
    handles.TwoD_1Q1Q_Spectrum2,...
    {'Units'},{handles.misc.units});
[handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
    handles.TwoD_1Q1Q_Spectrum3,...
    {'Units'},{handles.misc.units});
end
guidata(hObject,handles);
% --- Executes on button press in radiobutton_Units_PHz.
function radiobutton_Units_PHz_Callback(hObject, eventdata, handles)
% hObject    handle to radiobutton_Units_PHz (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hint: get(hObject,'Value') returns toggle state of radiobutton_Units_PHz
state=get(hObject,'Value');
if state==1
handles.misc.units='PHz';
[handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
    handles.TwoD_1Q1Q_Spectrum1,...
    {'Units'},{handles.misc.units});
[handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
    handles.TwoD_1Q1Q_Spectrum2,...
    {'Units'},{handles.misc.units});
[handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
    handles.TwoD_1Q1Q_Spectrum3,...
    {'Units'},{handles.misc.units});
end
guidata(hObject,handles);
% --------------------------------------------------------------------
function Menu_plot_settings_Callback(hObject, eventdata, handles)
% hObject    handle to Menu_plot_settings (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
set(handles.uipanel_plot_settings,'Visible','on');
% --- Executes on button press in radiobutton_plot_contour.
function radiobutton_plot_contour_Callback(hObject, eventdata, handles)
% hObject    handle to radiobutton_plot_contour (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
state=get(hObject,'Value');
if state==1
    handles.misc.contour='on';
elseif state==0
    handles.misc.contour='off';
end
[handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
    handles.TwoD_1Q1Q_Spectrum1,...
    {'Contour'},{handles.misc.contour});
[handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
    handles.TwoD_1Q1Q_Spectrum2,...
    {'Contour'},{handles.misc.contour});
[handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
    handles.TwoD_1Q1Q_Spectrum3,...
    {'Contour'},{handles.misc.contour});
guidata(hObject,handles);
% --------------------------------------------------------------------
function Menu_Plot_settings_countour_lines_Callback(hObject, eventdata, handles)
% hObject    handle to Menu_Plot_settings_countour_lines (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
set(handles.radiobutton_plot_contour,'Value',1);
handles.misc.contour='on';
[handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
    handles.TwoD_1Q1Q_Spectrum1,...
    {'Contour'},{handles.misc.contour});
[handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
    handles.TwoD_1Q1Q_Spectrum2,...
    {'Contour'},{handles.misc.contour});
[handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
    handles.TwoD_1Q1Q_Spectrum3,...
    {'Contour'},{handles.misc.contour});
guidata(hObject,handles);
function edit_number_of_lines_Callback(hObject, eventdata, handles)
% hObject    handle to edit_number_of_lines (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_number_of_lines as text
%        str2double(get(hObject,'String')) returns contents of edit_number_of_lines as a double
num_isovalues=str2double(get(hObject,'String'));
if floor(num_isovalues)==num_isovalues
    handles.misc.number_isovalues=num_isovalues;
    [handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
        handles.TwoD_1Q1Q_Spectrum1,...
        {'contour_isovalues'},{handles.misc.number_isovalues});
    [handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
        handles.TwoD_1Q1Q_Spectrum2,...
        {'contour_isovalues'},{handles.misc.number_isovalues});
    [handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
        handles.TwoD_1Q1Q_Spectrum3,...
        {'contour_isovalues'},{handles.misc.number_isovalues});
end
guidata(hObject,handles);
% --- Executes during object creation, after setting all properties.
function edit_number_of_lines_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_number_of_lines (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --- Executes on slider movement.
function slider_T_scan_Callback(hObject, eventdata, handles)
% hObject    handle to slider_T_scan (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'Value') returns position of slider
%        get(hObject,'Min') and get(hObject,'Max') to determine range of slider
SizeTimeDomainData=size(handles.maindata.TDdata.TimeDomainData);
set(hObject,'Min',1)
set(hObject,'Max',SizeTimeDomainData(1,3));
Max=get(hObject,'Max');
1000 set(hObject,'SliderStep',[1/(Max-1) 1/(Max-1)]);
1001 Tpos=get(hObject,'Value');
1002 handles.TDdata.Tpos=round(Tpos);
1003 round(Tpos)
1004 set(handles.text_T_scan,'String',['T = ' num2str(handles.maindata.TDdata.T_vector(handles.TDdata.Tpos)) ' fs']);
1005 [handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
1006         handles.TwoD_1Q1Q_Spectrum1,...
1007         {'Tpos'},{handles.TDdata.Tpos});
1008     [handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
1009         handles.TwoD_1Q1Q_Spectrum2,...
1010         {'Tpos'},{handles.TDdata.Tpos});
1011     [handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
1012         handles.TwoD_1Q1Q_Spectrum3,...
1013         {'Tpos'},{handles.TDdata.Tpos});
1014 guidata(hObject,handles);
1015 % --- Executes during object creation, after setting all properties.
1016 function slider_T_scan_CreateFcn(hObject, eventdata, handles)
1017 % hObject    handle to slider_T_scan (see GCBO)
1018 % eventdata  reserved - to be defined in a future version of MATLAB
1019 % handles    empty - handles not created until after all CreateFcns called
1020
1021 % Hint: slider controls usually have a light gray background.
1022 if isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1023     set(hObject,'BackgroundColor',[.9 .9 .9]);
1024 end
1025
1026
1027 guidata(hObject,handles);
1028 % --- Executes on button press in radiobutton_active_figure1.
1029 function radiobutton_active_figure1_Callback(hObject, eventdata, handles)
1030 % hObject    handle to radiobutton_active_figure1 (see GCBO)
1031 % eventdata  reserved - to be defined in a future version of MATLAB
1032 % handles    structure with handles and user data (see GUIDATA)
1033
1034 % Hint: get(hObject,'Value') returns toggle state of radiobutton_active_figure1
1035 state=get(hObject,'Value');
1036 if state==0;
1037 set(hObject,'Value',1);
1038 end
1039 handles.misc.active_figure=1;
1040 set(handles.radiobutton_active_figure3,'Value',0)
1041 set(handles.radiobutton_active_figure2,'Value',0)
1042 guidata(hObject,handles);
1043 % --- Executes during object creation, after setting all properties.
1044 function radiobutton_active_figure1_CreateFcn(hObject, eventdata, handles)
1045 % hObject    handle to radiobutton_active_figure1 (see GCBO)
1046 % eventdata  reserved - to be defined in a future version of MATLAB
1047 % handles    empty - handles not created until after all CreateFcns called
1048 % --- Executes on button press in radiobutton_active_figure3.
1049 handles.misc.active_figure=1;
1050 guidata(hObject,handles);
1051 function radiobutton_active_figure3_Callback(hObject, eventdata, handles)
1052 % hObject    handle to radiobutton_active_figure3 (see GCBO)
1053 % eventdata  reserved - to be defined in a future version of MATLAB
1054 % handles    structure with handles and user data (see GUIDATA)
1055 state=get(hObject,'Value');
1056 if state==0;
1057 set(hObject,'Value',1);
1058 end
1059 handles.misc.active_figure=3;
1060 set(handles.radiobutton_active_figure2,'Value',0)
1061 set(handles.radiobutton_active_figure1,'Value',0)
1062 guidata(hObject,handles);
1063 % --- Executes on button press in radiobutton_active_figure2.
1064 function radiobutton_active_figure2_Callback(hObject, eventdata, handles)
1065 % hObject    handle to radiobutton_active_figure2 (see GCBO)
1066 % eventdata  reserved - to be defined in a future version of MATLAB
1067 % handles    structure with handles and user data (see GUIDATA)
1068 state=get(hObject,'Value');
1069 if state==0;
1070 set(hObject,'Value',1);
1071 end
1072 handles.misc.active_figure=2;
1073 set(handles.radiobutton_active_figure3,'Value',0)
1074 set(handles.radiobutton_active_figure1,'Value',0)
1075 guidata(hObject,handles);
1076 % --------------------------------------------------------------------
1077 function Menu_Data_Def_ROI_Callback(hObject, eventdata, handles)
1078 % hObject    handle to Menu_Data_Def_ROI (see GCBO)
1079 % eventdata  reserved - to be defined in a future version of MATLAB
1080 % handles    structure with handles and user data (see GUIDATA)
1081 %add ROI to Roi list in listbox
1082 set(handles.panel_data_settings,'Visible','on');
1083
1084 guidata(hObject,handles);
1085 % --- Executes on button press in pushbutton_add_ROI.
1086 function pushbutton_add_ROI_Callback(hObject, eventdata, handles)
1087 % hObject    handle to pushbutton_add_ROI (see GCBO)
1088 % eventdata  reserved - to be defined in a future version of MATLAB
1089 % handles    structure with handles and user data (see GUIDATA)
1090 type=handles.ROI.type;
1091 if handles.misc.active_figure==1
1092 dat=handles.figure_1_data;
1093 ax=handles.TwoD_1Q1Q_Spectrum1;
1094 elseif handles.misc.active_figure==2
1095 dat=handles.figure_2_data;
1096 ax=handles.TwoD_1Q1Q_Spectrum2;
1097 elseif handles.misc.active_figure==3
1098 dat=handles.figure_3_data;
1099 ax=handles.TwoD_1Q1Q_Spectrum3;
1100 end
1101
1102 [x,y,local_mask]=TwoD_def_ROI(type,ax,dat.Domain,dat.tau_vector_image,...
1103     dat.t_vector_image,dat.w_tau_image,dat.w_t_image);
1104 str=['dX=' num2str([min(x), max(x)],' %.2f') ' dY=' num2str([min(y), max(y)],' %.2f')];
1105 contents = get(handles.listbox_ROIs,'String');
1106 contents{end+1} = str;
1107 set(handles.listbox_ROIs,'String',contents);
1108 set(handles.listbox_ROIs,'Value',size(contents,1))
1109 %add ROI in ROI data list
1110 if isempty(handles.ROI.ROI_data_x)
1111     handles.ROI.ROI_data_x{1}=x;
1112     handles.ROI.ROI_data_y{1}=y;
1113     %add ROI mask to ROI mask data list+
1114     handles.ROI.ROI_mask_data{1}=local_mask;
1115 else
1116     handles.ROI.ROI_data_x{end+1}=x;
1117     handles.ROI.ROI_data_y{end+1}=y;
1118     %add ROI mask to ROI mask data list+
1119     handles.ROI.ROI_mask_data{end+1}=local_mask;
1120 end
1121
1122 [handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
1123     handles.TwoD_1Q1Q_Spectrum1,...
1124     {'ROIdata'},{handles.ROI});
1125 [handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
1126     handles.TwoD_1Q1Q_Spectrum2,...
1127     {'ROIdata'},{handles.ROI});
1128 [handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
1129     handles.TwoD_1Q1Q_Spectrum3,...
1130     {'ROIdata'},{handles.ROI});
1131 guidata(hObject,handles);
1132 % --- Executes on selection change in listbox_ROIs.
1133 function listbox_ROIs_Callback(hObject, eventdata, handles)
1134 % hObject    handle to listbox_ROIs (see GCBO)
1135 % eventdata  reserved - to be defined in a future version of MATLAB
1136 % handles    structure with handles and user data (see GUIDATA)
1137
1138 % Hints: contents = cellstr(get(hObject,'String')) returns listbox_ROIs contents as cell array
1139 %        contents{get(hObject,'Value')} returns selected item from listbox_ROIs
1140 contents = cellstr(get(hObject,'String'));
1141 handles.ROI.selected_ROI=contents{get(hObject,'Value')};
1142 guidata(hObject,handles);
1143 % --- Executes during object creation, after setting all properties.
1144 function listbox_ROIs_CreateFcn(hObject, eventdata, handles)
1145 % hObject    handle to listbox_ROIs (see GCBO)
1146 % eventdata  reserved - to be defined in a future version of MATLAB
1147 % handles    empty - handles not created until after all CreateFcns called
1148
1149 % Hint: listbox controls usually have a white background on Windows.
1150 %       See ISPC and COMPUTER.
1151 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1152     set(hObject,'BackgroundColor','white');
1153 end
1154 % --- Executes on button press in radiobutton_square.
1155 function radiobutton_square_Callback(hObject, eventdata, handles)
1156 % hObject    handle to radiobutton_square (see GCBO)
1157 % eventdata  reserved - to be defined in a future version of MATLAB
1158 % handles    structure with handles and user data (see GUIDATA)
1159 state=get(hObject,'Value');
1160 if state==0
1161 set(hObject,'Value',1);
1162 end
1163 set(handles.radiobutton_manual_square,'Value',0);
1164 set(handles.radiobutton_Polygon,'Value',0);
1165 set(handles.radiobutton_fixed_size,'Value',0);
1166 handles.ROI.type='2 point input';
1167 guidata(hObject,handles);
1168 % --- Executes on button press in radiobutton_manual_square.
1169 function radiobutton_manual_square_Callback(hObject, eventdata, handles)
1170 % hObject    handle to radiobutton_manual_square (see GCBO)
1171 % eventdata  reserved - to be defined in a future version of MATLAB
1172 % handles    structure with handles and user data (see GUIDATA)
1173 state=get(hObject,'Value');
1174 if state==0
1175 set(hObject,'Value',1);
1176 end
1177 set(handles.radiobutton_square,'Value',0);
1178 set(handles.radiobutton_Polygon,'Value',0);
1179 set(handles.radiobutton_fixed_size,'Value',0);
1180 handles.ROI.type='manual input';
1181 guidata(hObject,handles);
1182 % --- Executes on button press in radiobutton_fixed_size.
1183 function radiobutton_fixed_size_Callback(hObject, eventdata, handles)
1184 % hObject    handle to radiobutton_fixed_size (see GCBO)
1185 % eventdata  reserved - to be defined in a future version of MATLAB
1186 % handles    structure with handles and user data (see GUIDATA)
1187 state=get(hObject,'Value');
1188 if state==0
1189 set(hObject,'Value',1);
1190 end
1191 set(handles.radiobutton_square,'Value',0);
1192 set(handles.radiobutton_Polygon,'Value',0);
1193 set(handles.radiobutton_manual_square,'Value',0);
1194 handles.ROI.type='fixed size';
1195 guidata(hObject,handles);
1196 % --- Executes on button press in radiobutton_Polygon.
1197 function radiobutton_Polygon_Callback(hObject, eventdata, handles)
1198 % hObject    handle to radiobutton_Polygon (see GCBO)
1199 % eventdata  reserved - to be defined in a future version of MATLAB
1200 % handles    structure with handles and user data (see GUIDATA)
1201 state=get(hObject,'Value');
1202 if state==0
1203 set(hObject,'Value',1);
1204 end
1205 set(handles.radiobutton_square,'Value',0);
1206 set(handles.radiobutton_fixed_size,'Value',0);
1207 set(handles.radiobutton_manual_square,'Value',0);
1208 handles.ROI.type='polygon';
1209 guidata(hObject,handles);
1210 % --- Executes during object creation, after setting all properties.
1211 function radiobutton_square_CreateFcn(hObject, eventdata, handles)
1212 % hObject    handle to radiobutton_square (see GCBO)
1213 % eventdata  reserved - to be defined in a future version of MATLAB
1214 % handles    empty - handles not created until after all CreateFcns called
1215 handles.ROI.type='2 point input';
1216 guidata(hObject,handles);
1217 % --- Executes on button press in pushbutton_delete_ROI.
1218 function pushbutton_delete_ROI_Callback(hObject, eventdata, handles)
1219 % hObject    handle to pushbutton_delete_ROI (see GCBO)
1220 % eventdata  reserved - to be defined in a future version of MATLAB
1221 % handles    structure with handles and user data (see GUIDATA)
1222
1223 %Current ROI list content
1224 contents = get(handles.listbox_ROIs,'String');
1225 %Current selected ROI is handles.selected_ROI, if no ROI has been selected,
1226 %use first item
1227    truefalse=isfield(handles.ROI,'selected_ROI');
1228   if truefalse==0
1229
1230       warndlg('You have to create a ROI first or click on the ROI you want to delete.');
1231       error('You have to create a ROI first or click on the ROI you want to delete.');
1232   end
1233 %Nasty fix that deleting the last entry will not destroy everything...
1234 row=get(handles.listbox_ROIs,'Value');
1235
1236 contents(row,:)=[];
1237 %Write new ROI_list
1238 set(handles.listbox_ROIs,'String',contents);
1239 if size(handles.listbox_ROIs,1)>0
1240     set(handles.listbox_ROIs,'Value',size(handles.listbox_ROIs,1));
1241 end
1242
1243
1244 %update ROI_data_x and ROI_data_y
1245 handles.ROI.ROI_data_x(row)=[];
1246 handles.ROI.ROI_data_y(row)=[];
1247 %update mask cell array
1248 handles.ROI.ROI_mask_data(row)=[];
1249
1250 [handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
1251     handles.TwoD_1Q1Q_Spectrum1,...
1252     {'ROIdata'},{handles.ROI});
1253 [handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
1254     handles.TwoD_1Q1Q_Spectrum2,...
1255     {'ROIdata'},{handles.ROI});
1256 [handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
1257     handles.TwoD_1Q1Q_Spectrum3,...
1258     {'ROIdata'},{handles.ROI});
1259
1260 guidata(hObject,handles);
1261 % --- Executes on button press in pushbutton_calc_T_scan.
1262 function pushbutton_calc_T_scan_Callback(hObject, eventdata, handles)
1263 % hObject    handle to pushbutton_calc_T_scan (see GCBO)
1264 % eventdata  reserved - to be defined in a future version of MATLAB
1265 % handles    structure with handles and user data (see GUIDATA)
1266 if handles.misc.active_figure==1
1267 dat=handles.figure_1_data;
1268 ax=handles.TwoD_1Q1Q_Spectrum1;
1269 elseif handles.misc.active_figure==2
1270 dat=handles.figure_2_data;
1271 ax=handles.TwoD_1Q1Q_Spectrum2;
1272 elseif handles.misc.active_figure==3
1273 dat=handles.figure_3_data;
1274 ax=handles.TwoD_1Q1Q_Spectrum3;
1275 end
1276
1277 T_scan_evaluation(dat);
1278 guidata(hObject,handles);
1279 % --------------------------------------------------------------------
1280 function Menu_Data_Gamma_value_Callback(hObject, eventdata, handles)
1281 % hObject    handle to Menu_Data_Gamma_value (see GCBO)
1282 % eventdata  reserved - to be defined in a future version of MATLAB
1283 % handles    structure with handles and user data (see GUIDATA)
1284 set(handles.panel_data_settings,'Visible','on');
1285 guidata(hObject,handles);
1286 function edit_gamma_Callback(hObject, eventdata, handles)
1287 % hObject    handle to edit_gamma (see GCBO)
1288 % eventdata  reserved - to be defined in a future version of MATLAB
1289 % handles    structure with handles and user data (see GUIDATA)
1290
1291 % Hints: get(hObject,'String') returns contents of edit_gamma as text
1292 %        str2double(get(hObject,'String')) returns contents of edit_gamma as a double
1293 handles.misc.gamma=str2double(get(hObject,'String'));
1294 if handles.misc.gamma<0 || 1<handles.misc.gamma
1295     msgbox('Gamma must be between 0 and 1!');
1296     handles.misc.gamma=0;
1297 end
1298 [handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
1299     handles.TwoD_1Q1Q_Spectrum1,...
1300     {'gamma'},{handles.misc.gamma});
1301 [handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
1302     handles.TwoD_1Q1Q_Spectrum2,...
1303     {'gamma'},{handles.misc.gamma});
1304 [handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
1305     handles.TwoD_1Q1Q_Spectrum3,...
1306     {'gamma'},{handles.misc.gamma});
1307
1308
1309 guidata(hObject,handles);
1310 % --- Executes during object creation, after setting all properties.
1311 function edit_gamma_CreateFcn(hObject, eventdata, handles)
1312 % hObject    handle to edit_gamma (see GCBO)
1313 % eventdata  reserved - to be defined in a future version of MATLAB
1314 % handles    empty - handles not created until after all CreateFcns called
1315
1316 % Hint: edit controls usually have a white background on Windows.
1317 %       See ISPC and COMPUTER.
1318 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1319     set(hObject,'BackgroundColor','white');
1320 end
1321 function edit_lambda0_Callback(hObject, eventdata, handles)
1322 % hObject    handle to edit_lambda0 (see GCBO)
1323 % eventdata  reserved - to be defined in a future version of MATLAB
1324 % handles    structure with handles and user data (see GUIDATA)
1325
1326 % Hints: get(hObject,'String') returns contents of edit_lambda0 as text
1327 %        str2double(get(hObject,'String')) returns contents of edit_lambda0 as a double
1328 handles.misc.centerwavelength= str2double(get(hObject,'String'));
1329 handles.misc.center_w=2*pi*299792458/(handles.misc.centerwavelength*1e-9)*1e-15;
1330
1331 [handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
1332     handles.TwoD_1Q1Q_Spectrum1,...
1333     {'omega_center'},{handles.misc.center_w});
1334 [handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
1335     handles.TwoD_1Q1Q_Spectrum2,...
1336     {'omega_center'},{handles.misc.center_w});
1337 [handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
1338     handles.TwoD_1Q1Q_Spectrum3,...
1339     {'omega_center'},{handles.misc.center_w});
1340
1341 guidata(hObject,handles);
1342 % --- Executes during object creation, after setting all properties.
1343 function edit_lambda0_CreateFcn(hObject, eventdata, handles)
1344 % hObject    handle to edit_lambda0 (see GCBO)
1345 % eventdata  reserved - to be defined in a future version of MATLAB
1346 % handles    empty - handles not created until after all CreateFcns called
1347
1348 % Hint: edit controls usually have a white background on Windows.
1349 %       See ISPC and COMPUTER.
1350 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1351     set(hObject,'BackgroundColor','white');
1352 end
1353 % --- Executes on slider movement.
1354 function slider_variable_scan_Callback(hObject, eventdata, handles)
1355 % hObject    handle to slider_variable_scan (see GCBO)
1356 % eventdata  reserved - to be defined in a future version of MATLAB
1357 % handles    structure with handles and user data (see GUIDATA)
1358
1359 % Hints: get(hObject,'Value') returns position of slider
1360 %        get(hObject,'Min') and get(hObject,'Max') to determine range of slider
1361 %SizeTimeDomainData=size(handles.maindata.TDdata.TimeDomainData);
1362 % set(hObject,'Min',1)
1363 % set(hObject,'Max',SizeTimeDomainData(1,3));
1364 % Max=get(hObject,'Max');
1365 % set(hObject,'SliderStep',[1/(Max-1) 1/(Max-1)]);
1366 Varpos=get(hObject,'Value');
1367 handles.TDdata.Varpos(1)=round(Varpos);
1368 set(handles.text_variable_scan_2,'String',['Variable = ' num2str(handles.maindata.TDdata.variable_vector(handles.TDdata.Varpos(1))) ' [arb.u.]']);
1369 [handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
1370         handles.TwoD_1Q1Q_Spectrum1,...
1371         {'TimeDomainData','Varpos'},{handles.maindata.TDdata.TimeDomainData, handles.TDdata.Varpos(1)});
1372     [handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
1373         handles.TwoD_1Q1Q_Spectrum2,...
1374         {'TimeDomainData','Varpos'},{handles.maindata.TDdata.TimeDomainData,handles.TDdata.Varpos(1)});
1375     [handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
1376         handles.TwoD_1Q1Q_Spectrum3,...
1377         {'TimeDomainData','Varpos'},{handles.maindata.TDdata.TimeDomainData,handles.TDdata.Varpos});
1378 guidata(hObject,handles);
1379 % --- Executes during object creation, after setting all properties.
1380 function slider_variable_scan_CreateFcn(hObject, eventdata, handles)
1381 % hObject    handle to slider_variable_scan (see GCBO)
1382 % eventdata  reserved - to be defined in a future version of MATLAB
1383 % handles    empty - handles not created until after all CreateFcns called
1384
1385 % Hint: slider controls usually have a light gray background.
1386 if isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1387     set(hObject,'BackgroundColor',[.9 .9 .9]);
1388 end
1389
1390
1391 guidata(hObject,handles);
1392 % --- Executes during object creation, after setting all properties.
1393 function text_variable_scan_2_CreateFcn(hObject, eventdata, handles)
1394 % hObject    handle to text_variable_scan_2 (see GCBO)
1395 % eventdata  reserved - to be defined in a future version of MATLAB
1396 % handles    empty - handles not created until after all CreateFcns called
1397 maindata=guidata(CMDSworld);
1398
1399 handles.maindata=maindata;
1400 NumDim=ndims(handles.maindata.TDdata.TimeDomainData);
1401 if NumDim>=5
1402     set(hObject,'Visible','on');
1403     set(hObject,'String',['Variable = ' num2str(maindata.TDdata.variable_vector(1)) ' [arb.u.]']);
1404 end
1405 % --- Executes on button press in radiobutton_Double_omega_tau.
1406 function radiobutton_Double_omega_tau_Callback(hObject, eventdata, handles)
1407 % hObject    handle to radiobutton_Double_omega_tau (see GCBO)
1408 % eventdata  reserved - to be defined in a future version of MATLAB
1409 % handles    structure with handles and user data (see GUIDATA)
1410 state=get(hObject,'Value');
1411 if state==1;
1412     Double_omega_tau='on';
1413 elseif state==0
1414     Double_omega_tau='off';
1415 end
1416
1417     [handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
1418         handles.TwoD_1Q1Q_Spectrum1,...
1419         {'Double_omega_tau'},{Double_omega_tau});
1420     [handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
1421         handles.TwoD_1Q1Q_Spectrum2,...
1422         {'Double_omega_tau'},{Double_omega_tau});
1423     [handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
1424         handles.TwoD_1Q1Q_Spectrum3,...
1425         {'Double_omega_tau'},{Double_omega_tau});
1426 guidata(hObject,handles);
1427 % --- Executes on button press in radiobutton_Double_omega_t.
1428 function radiobutton_Double_omega_t_Callback(hObject, eventdata, handles)
1429 % hObject    handle to radiobutton_Double_omega_t (see GCBO)
1430 % eventdata  reserved - to be defined in a future version of MATLAB
1431 % handles    structure with handles and user data (see GUIDATA)
1432 state=get(hObject,'Value');
1433 if state==1;
1434     Double_omega_t='on';
1435 elseif state==0
1436     Double_omega_t='off';
1437 end
1438
1439     [handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
1440         handles.TwoD_1Q1Q_Spectrum1,...
1441         {'Double_omega_t'},{Double_omega_t});
1442     [handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
1443         handles.TwoD_1Q1Q_Spectrum2,...
1444         {'Double_omega_t'},{Double_omega_t});
1445     [handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
1446         handles.TwoD_1Q1Q_Spectrum3,...
1447         {'Double_omega_t'},{Double_omega_t});
1448 guidata(hObject,handles);
1449 % --- Executes on button press in radiobutton_spectrum_flip_w_tau.
1450 function radiobutton_spectrum_flip_w_tau_Callback(hObject, eventdata, handles)
1451 state= get(hObject,'Value'); % returns toggle state of radiobutton_spectrum_flip_w_tau
1452 if state==1
1453    handles.misc.Flip_w_tau='on';
1454 elseif state==0
1455    handles.misc.Flip_w_tau='off';
1456 end
1457 [handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
1458     handles.TwoD_1Q1Q_Spectrum1,...
1459     {'Flip_w_tau'},{handles.misc.Flip_w_tau});
1460 [handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
1461     handles.TwoD_1Q1Q_Spectrum2,...
1462     {'Flip_w_tau'},{handles.misc.Flip_w_tau});
1463 [handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
1464     handles.TwoD_1Q1Q_Spectrum3,...
1465     {'Flip_w_tau'},{handles.misc.Flip_w_tau});
1466 guidata(hObject,handles);
1467
1468
1469
1470 % --- Executes on button press in radiobutton_spectrum_flip_w_t.
1471 function radiobutton_spectrum_flip_w_t_Callback(hObject, eventdata, handles)
1472 % hObject    handle to radiobutton_spectrum_flip_w_t (see GCBO)
1473 % eventdata  reserved - to be defined in a future version of MATLAB
1474 % handles    structure with handles and user data (see GUIDATA)
1475 state= get(hObject,'Value'); % returns toggle state of radiobutton_spectrum_flip_w_tau
1476 if state==1
1477    handles.misc.Flip_w_t='on';
1478 elseif state==0
1479    handles.misc.Flip_w_t='off';
1480 end
1481 [handles.figure_1_data]=UpdateFigure(handles.figure_1_data,...
1482     handles.TwoD_1Q1Q_Spectrum1,...
1483     {'Flip_w_t'},{handles.misc.Flip_w_t});
1484 [handles.figure_2_data]=UpdateFigure(handles.figure_2_data,...
1485     handles.TwoD_1Q1Q_Spectrum2,...
1486     {'Flip_w_t'},{handles.misc.Flip_w_t});
1487 [handles.figure_3_data]=UpdateFigure(handles.figure_3_data,...
1488     handles.TwoD_1Q1Q_Spectrum3,...
1489     {'Flip_w_t'},{handles.misc.Flip_w_t});
1490 guidata(hObject,handles);
1491
1492
1493 % --------------------------------------------------------------------
1494 function Menu_Plot_settings_flip_axes_Callback(hObject, eventdata, handles)
1495 % hObject    handle to Menu_Plot_settings_flip_axes (see GCBO)
1496 % eventdata  reserved - to be defined in a future version of MATLAB
1497 % handles    structure with handles and user data (see GUIDATA)
1498 set(handles.uipanel_plot_settings,'Visible','on');
1499
1500
1501