Description of check_input_data
Home > CMDSworld > subguis > subfunctions_time_domain_maps > check_input_data.m
check_input_data
PURPOSE
SYNOPSIS
function[outputboolean,Size_TimeDomainData]=check_input_data(TimeDomainData,tau_vector,T_vector,t_vector)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Time_Domain_Maps TIME_DOMAIN_MAPS M-file for Time_Domain_Maps.fig
Time_Domain_Maps_backup TIME_DOMAIN_MAPS M-file for Time_Domain_Maps.fig
TwoDspec1Q1Q TWODSPEC1Q1Q MATLAB code for TwoDspec1Q1Q.fig
SOURCE CODE
function[outputboolean,Size_TimeDomainData]=check_input_data(TimeDomainData,tau_vector,T_vector,t_vector)
Size_TimeDomainData=size(TimeDomainData);
if ~isempty(TimeDomainData) && ~isempty(tau_vector) && ~isempty(T_vector) && ~isempty (t_vector)
   if length(tau_vector)==Size_TimeDomainData(1,2)
       outputboolean=true;
   end
   if length(T_vector)==Size_TimeDomainData(1,2)
       outputboolean=true;
   end
   if length(t_vector)==Size_TimeDomainData(1,2)
        outputboolean=true;
   end
else
   outputboolean=false;
end